In [64]:
# type: ignore
import pandas as pd 
import numpy as np   
import matplotlib.pyplot as plt

In [65]:
dataset = pd.read_csv("Data.csv")
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [66]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [67]:
dataset.tail()

Country   Age   Salary Purchased
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [68]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values
x, y

(array([['France', 44.0, 72000.0],
        ['Spain', 27.0, 48000.0],
        ['Germany', 30.0, 54000.0],
        ['Spain', 38.0, 61000.0],
        ['Germany', 40.0, nan],
        ['France', 35.0, 58000.0],
        ['Spain', nan, 52000.0],
        ['France', 48.0, 79000.0],
        ['Germany', 50.0, 83000.0],
        ['France', 37.0, 67000.0]], dtype=object),
 array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
       dtype=object))

In [69]:
pd.DataFrame(x, y)

0     1        2
No    France  44.0  72000.0
Yes    Spain  27.0  48000.0
No   Germany  30.0  54000.0
No     Spain  38.0  61000.0
Yes  Germany  40.0      NaN
Yes   France  35.0  58000.0
No     Spain   NaN  52000.0
Yes   France  48.0  79000.0
No   Germany  50.0  83000.0
Yes   France  37.0  67000.0

In [70]:
skew1 = dataset['Age'].skew()
skew2 = dataset['Salary'].skew()
skew1, skew2

(-0.009950482487719648, 0.3926624309834449)

In [71]:
# type: ignore
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [72]:
# type: ignore
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [73]:
pd.DataFrame(x)

0    1    2          3             4
0  1.0  0.0  0.0       44.0       72000.0
1  0.0  0.0  1.0       27.0       48000.0
2  0.0  1.0  0.0       30.0       54000.0
3  0.0  0.0  1.0       38.0       61000.0
4  0.0  1.0  0.0       40.0  63777.777778
5  1.0  0.0  0.0       35.0       58000.0
6  0.0  0.0  1.0  38.777778       52000.0
7  1.0  0.0  0.0       48.0       79000.0
8  0.0  1.0  0.0       50.0       83000.0
9  1.0  0.0  0.0       37.0       67000.0

In [74]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [75]:
# type: ignore
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
y = le.fit_transform(y)
pd.DataFrame(y)

0
0  0
1  1
2  0
3  0
4  1
5  1
6  0
7  1
8  0
9  1

In [76]:
x, y

(array([[1.0, 0.0, 0.0, 44.0, 72000.0],
        [0.0, 0.0, 1.0, 27.0, 48000.0],
        [0.0, 1.0, 0.0, 30.0, 54000.0],
        [0.0, 0.0, 1.0, 38.0, 61000.0],
        [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
        [1.0, 0.0, 0.0, 35.0, 58000.0],
        [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
        [1.0, 0.0, 0.0, 48.0, 79000.0],
        [0.0, 1.0, 0.0, 50.0, 83000.0],
        [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object),
 array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1]))

In [77]:
# type: ignore
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [78]:
x_train

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0]], dtype=object)

In [79]:
x_test

array([[0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0]], dtype=object)

In [80]:
y_train

array([0, 1, 0, 1, 1, 0, 1, 1])

In [81]:
y_test

array([0, 0])

In [82]:
# type: ignore
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [83]:
x_train

array([[1.0, 0.0, 0.0, 1.011213445354745, 1.0326014773154037],
       [0.0, 0.0, 1.0, -1.6222445485052714, -1.378662512956241],
       [0.0, 1.0, 0.0, -1.1575166672358568, -0.7758465153883298],
       [1.0, 0.0, 0.0, -0.382970198453499, -0.37396918367638904],
       [0.0, 1.0, 0.0, 0.3915762703288588, 0.20652029546308134],
       [0.0, 0.0, 1.0, 0.2022426890709492, -0.9767851812443002],
       [1.0, 0.0, 0.0, -0.07315161094055589, 0.5302548126754778],
       [1.0, 0.0, 0.0, 1.6308506203806312, 1.7358868078113001]],
      dtype=object)

In [84]:
x_test

array([[0.0, 0.0, 1.0, 0.08175768281591567, -0.07256118489243343],
       [0.0, 1.0, 0.0, 1.940669207893574, 2.137764139523241]],
      dtype=object)